export const GET_ARTICLE = 'GET_ARTICLE';
export const GET_CURRENT_POST_WITH_COMMETS = 'GET_CURRENT_POST_WITH_COMMETS';
export const ADD_NEW_COMMENT_FOR_POST = 'ADD_NEW_COMMENT_FOR_POST';
export const ADD_NEW_POST = 'ADD_NEW_POST';
export const EDIT_POST = 'EDIT_POST';
